# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: S:/4-19-18_FIX/src/constraints.xdc

# Block Designs: S:/4-19-18_FIX/src/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: S:/4-19-18_FIX/src/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_ultrasonic_sensor_axi_0_0/design_1_ultrasonic_sensor_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ultrasonic_sensor_axi_0_0 || ORIG_REF_NAME==design_1_ultrasonic_sensor_axi_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_echo_pulse_measurer_0_0/design_1_echo_pulse_measurer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_echo_pulse_measurer_0_0 || ORIG_REF_NAME==design_1_echo_pulse_measurer_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_echo_pulse_measurer_1_0/design_1_echo_pulse_measurer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_echo_pulse_measurer_1_0 || ORIG_REF_NAME==design_1_echo_pulse_measurer_1_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_echo_pulse_measurer_2_0/design_1_echo_pulse_measurer_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_echo_pulse_measurer_2_0 || ORIG_REF_NAME==design_1_echo_pulse_measurer_2_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_motor_axi_0_0/design_1_motor_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_motor_axi_0_0 || ORIG_REF_NAME==design_1_motor_axi_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_imu_wrapper_0_0/design_1_imu_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_imu_wrapper_0_0 || ORIG_REF_NAME==design_1_imu_wrapper_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_encoder_reader_top_0_0/design_1_encoder_reader_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_encoder_reader_top_0_0 || ORIG_REF_NAME==design_1_encoder_reader_top_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_encoder_reader_top_1_0/design_1_encoder_reader_top_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_encoder_reader_top_1_0 || ORIG_REF_NAME==design_1_encoder_reader_top_1_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_encoder_reader_top_2_0/design_1_encoder_reader_top_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_encoder_reader_top_2_0 || ORIG_REF_NAME==design_1_encoder_reader_top_2_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_encoder_reader_top_3_0/design_1_encoder_reader_top_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_encoder_reader_top_3_0 || ORIG_REF_NAME==design_1_encoder_reader_top_3_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_pwm_generator_0_0/design_1_pwm_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_generator_0_0 || ORIG_REF_NAME==design_1_pwm_generator_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_pwm_generator_1_0/design_1_pwm_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_generator_1_0 || ORIG_REF_NAME==design_1_pwm_generator_1_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_pwm_generator_2_0/design_1_pwm_generator_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_generator_2_0 || ORIG_REF_NAME==design_1_pwm_generator_2_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_pwm_generator_3_0/design_1_pwm_generator_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pwm_generator_3_0 || ORIG_REF_NAME==design_1_pwm_generator_3_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_led_axi_0_0/design_1_led_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_axi_0_0 || ORIG_REF_NAME==design_1_led_axi_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_led_error_0_0/design_1_led_error_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_error_0_0 || ORIG_REF_NAME==design_1_led_error_0_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_led_error_1_0/design_1_led_error_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_error_1_0 || ORIG_REF_NAME==design_1_led_error_1_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_led_error_2_0/design_1_led_error_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_led_error_2_0 || ORIG_REF_NAME==design_1_led_error_2_0}]

# IP: S:/4-19-18_FIX/src/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: s:/4-19-18_FIX/src/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# XDC: S:/4-19-18_FIX/src/design_1_ooc.xdc
