# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/constraints.xdc

# Block Designs: C:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_blink_0_0/design_1_blink_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blink_0_0 || ORIG_REF_NAME==design_1_blink_0_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_receiver_wrapper_0_0/design_1_receiver_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_receiver_wrapper_0_0 || ORIG_REF_NAME==design_1_receiver_wrapper_0_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_imu_wrapper_0_0/design_1_imu_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_imu_wrapper_0_0 || ORIG_REF_NAME==design_1_imu_wrapper_0_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# IP: c:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2}]

# XDC: C:/Users/zdw7287/Downloads/rover-dev/firmware/baseline/src/design_1_ooc.xdc
